### ISSUE TITLE
Range option for Maiden of Virtue

### ISSUE THREAD

**Issue by jdelvare** [DeadlyBossMods/DBM-TBC-Classic#101]
**Describe the bug**
In the Karazhan > Maiden of Virtue module configuration page, in the Misc section there's an option to enable a range check (10) for the Holy Fire spell. However, the spell cast by Maiden which bounces from player to player is not Holy Fire (29522) but Holy Wrath (32445). So I think the AddRangeFrameOption call should use the Holy Wrath ID?

If I'm correct then here's a patch you can apply to fix the issue.

[dbm-karazhan-maiden-fix-range-spell-id.patch.txt](https://github.com/DeadlyBossMods/DBM-TBC-Classic/files/8007650/dbm-karazhan-maiden-fix-range-spell-id.patch.txt)

**Comment by MysticalOS** [comment]
You were right about ID,, i double checked it on a random log on WCL
