### ISSUE TITLE
Mother Sharaz static arrow position

### ISSUE THREAD

**Issue by GHsalles** [DeadlyBossMods/DBM-TBC-Classic#106]
When I get FA  (Fatal Attraction) I get my mark and the static arrow will appear as supposed to do, but the position where the arrow appears is not a good one (at the bottom right corner for me). 

 I'd like if it's possible to get an option to move the arrow freely before the raid.

**Comment by QartemisT** [comment]
You can find the option to move the arrow under `/dbm`, options, and then Core & GUI :)
