### ISSUE TITLE
Hyjal Waves inaccurate

### ISSUE THREAD

**Issue by Scentaur2020** [DeadlyBossMods/DBM-TBC-Classic#114]
The trash mobs listed for the incoming waves in Mt. Hyjal are inaccurate for all bosses in TBC-Classic.

**Which version of DeadlyBossMods are you using?**  2.5.4

**Was it working in a previous version? If yes, which was the last good one?**   I don't think it's been working in TBC-Classic correctly for the incoming trash mobs each wave since Hyjal was released.

**Additional context**

**Comment by MysticalOS** [comment]
news to me, i even got reports they were all right before. You'll have to be more specific which waves are wrong for which boss.

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DBM-TBC-Classic/pull/83 was issue that showed wave info from hyjal PTR

**Comment by Scentaur2020** [comment]
I will try recording my next Hyjal run (which looks to be the 25th for me since we alternate with BT) so I can go back through it and let you know specifics. It's too difficult for me to make a note of during the raid with everything going on, as you can imagine. :)

**Comment by BigMeanGiraffe** [comment]
Also having this issue, wave descriptions are inaccurate.

**Comment by Road-block** [comment]
They weren't inaccurate for us and I'm sorry I didn't see this earlier.

It's not a big deal in the grand scheme of things but the wave description was useful for us to remind the raid what we're doing next (move to bunker/tower or "everyone go gargoyles at back, tanks will bring front to you" or whatever each particular raid chooses to do)

If you're going to remove the only useful piece of information from the waves just remove the wave announcements entirely.

The default worldstate frame up top shows wave number and number of enemies incoming anyway.
I don't understand this change 😕
