### ISSUE TITLE
Corrupted Mind tracker does not work properly

### ISSUE THREAD

**Issue by silverhawke249** [DeadlyBossMods/DBM-TBC-Classic#12]
**Describe the bug**
Our raid uses alphabetical order for healing on Loatheb. The cooldown timer does not start consistently when heals were cast (and healers get afflicted with Corrupted Mind).

**Screenshots**
![image](https://user-images.githubusercontent.com/50395934/119427055-edc91d80-bd3c-11eb-99da-d3b55e056159.png)
Of note here, I have healing on cooldown, but the info frame says I'm off cooldown.

**Which version of DeadlyBossMods are you using?**
2.5.3-bc

**Comment by MysticalOS** [comment]
@venuatu ?

**Comment by MysticalOS** [comment]
Or maybe @QartemisT if it's a regression from going back to spellids but spellId not correct (or some missing?)

**Comment by silverhawke249** [comment]
![image](https://user-images.githubusercontent.com/50395934/119588655-d86af680-be03-11eb-8e1d-c522d2483671.png)
Still doesn't work, except this time everyone's timers broke instead of non-priests.

**Comment by QartemisT** [comment]
This should be properly fixed now as of the latest alpha :)
