### ISSUE TITLE
Sapphiron Frost Breath Alert

### ISSUE THREAD

**Issue by stratoru** [DeadlyBossMods/DBM-TBC-Classic#13]
Greetings! Currently, the alert for Sapphiron beginning to cast Frost Breath (AKA, after 5 Frost Bolts she begins casting Frost Breath during Air Phase) is bugged and hasn't worked over the last few days at minimum.  It doesn't seem to detect that she is casting Frost Breath at all and no alert is sent. I've confirmed this is bugged for others as well, not just myself.

**Comment by stratoru** [comment]
I know next to nothing about coding in general, but a quick glance at the Sapphiron.lua may reveal the reason. It appears the spellID for Life Drain (28542) is being used in Line 118 where I think you intended to define Frost Breath? The correct spellID for Frost Breath is 28524, which is very similar to the spellID used for Life Drain and is perhaps where the error was made. 

In the pre-tbc version of DBM you had the line as 
`if args.spellName == frostBreath and args:IsSrcTypeHostile() then -- Frost Breath`
and in the latest version of DBM you have the equivalent line as 
`if args.spellId == 28542 and args:IsSrcTypeHostile() then -- Frost Breath`

Hope this helps you with the correction (assuming this is truly the cause).

**Comment by QartemisT** [comment]
Thanks for the report, will have a fix out shortly
