### ISSUE TITLE
Gruul's Lair - Gruul Encounter - Range needs to be 15+

### ISSUE THREAD

**Issue by vertx66** [DeadlyBossMods/DBM-TBC-Classic#21]
Very simple fix for the range indicator on the fight.

Update lines 30 to 38 to the following

mod:AddRangeFrameOption(18, 33654)

function mod:OnCombatStart(delay)
	timerGrowthCD:Start(-delay)
	timerGroundSlamCD:Start(40-delay)
	if self.Options.RangeFrame then
		DBM.RangeCheck:Show(18)
	end
end

Range is 15+ for the fight, not 11. 

Cheers

**Comment by MysticalOS** [comment]
when I raided in original TBC the general rule of thumb was being > 11 was ok. yeah the max falloff is 20 yards technicaly (https://tbc.wowhead.com/spell=33671/shatter). But the falloff has multiple thresholds. It's a scale. It's not just 9000 damage until 20 yards. it's 9000 damage on top of another players head all the way down to 2000 damage at edge of the fall off.

>20 no damage but > 10 was survible and everyone could pop their own bandage after it and no deaths. it's pretty hard for 25 people to spread out 18 yards. outright unrealistic if I recall. But yes obviously spreading out the most possible is ideal, but i felt like the mod should mostly aim to achieve surviable. my experience in past at least (maybe gamers smarter in 2021 though) is that if it was set higher than 11 people were moving around too much and actually causing more deaths than if they were just happy with the "enough to survive and bandage after" strat.

I'll leave this issue open to more discussion though. I want ot hear more players thoughts

**Comment by vertx66** [comment]
We literally cleared it last night and 11 was not sufficient.

**Comment by MysticalOS** [comment]
Were you using level 68s in greens? Or a bunch of people not trained in first aid? something along those lines I can see 11 not being sufficient the very first week of BCC, but in general it should be sufficient enough to survive if high health and not undergeared.

We're already planning to add a user toggle to allow users to switch between 11 and 18 though, giving users control of their preference, but 11 will stay as an option

**Comment by vertx66** [comment]
Full guild of Naxx geared + numerous players with kara and heroic dungeon loot. But hey you do, not looking for a pissing contest. Just saying 11 at this point was working for us and 15 (18) was what was needed

**Comment by isitLoVe** [comment]
Tried Gruul today with 15 range, frame was empty but still took about 2k dmg. I also think 11 is not enough.

**Comment by QartemisT** [comment]
Added option :)
