### ISSUE TITLE
Timer Bug

### ISSUE THREAD

**Issue by Scrappy887** [DeadlyBossMods/DBM-TBC-Classic#48]
No matter what I put in the timer it always starts a 10 second timer.
/dbm pull 20 seconds
/pull 20 seconds

I am using DBM version 2.5.2

It has been doing this for me since classic and I cannot figure out why. Please help1!!!

**Comment by MysticalOS** [comment]
Doing code review and testing myself, I cannot reproduce this.

DBM 2.5.2 is ancient as hell though. Game version is at 2.5.2 but DBM is at 2.5.12

**Comment by Scrappy887** [comment]
Sorry i am at 2.5.12

**Comment by MysticalOS** [comment]
Still don't think the problem is DBM, another addon is breaking it probably. Using any timer replacement weak auras?

**Comment by Scrappy887** [comment]
None at all for a pulltimer

**Comment by Scrappy887** [comment]
I have had the issue since AQ40/Naxx

**Comment by MysticalOS** [comment]
What did you install during AQ40/naxx?

You tried disabling other addons? Have you tried doing a pull timer when not in a group to rule out trolling?

I just don't see anything that'd cause this to break outside of an addon breaking DBM or another person trolling you.

**Comment by Scrappy887** [comment]
I have not tried disabling what I am using currently, Do you know offhand any names of addons that might cause an issue with DBM?

**Comment by Scrappy887** [comment]
I deleted the addon and reinstalled and it looks like it fixed everything.

**Comment by Scrappy887** [comment]
On a side note I do notice when trying to use a /dbm pull 20 seconds macro  it only does a 10 second counter for me

**Comment by QartemisT** [comment]
Just do `/dbm pull 20` :)
