### ISSUE TITLE
Is there any chance that DBM is causing this issue?

### ISSUE THREAD

**Issue by denkololz** [DeadlyBossMods/DBM-TBC-Classic#51]
So, ive been sturggling alot in TBC-Classic to Move people to different raid groups **IN** combat, eventually i got it to work and apaprently i had some addon causing the issue.. However after updating DBM along with some other addons the issue is back once again. I read online that people had some issue with DBM in classic regarding the same issue and was just wondering if theres any chance its DBM? Im not very knowledgeable when it comes to this kinda stuff so figured id ask here..

**Comment by MysticalOS** [comment]
it's an issue that's really blizzards fault, it'll just blame random different addons for complex to explain reasons. there is literally nothing DBM is doing to cause this.

**Comment by denkololz** [comment]
Ok thanks for the help! Will try to dig further.
________________________________
