### ISSUE TITLE
2.5.12-10-gb11edb6-bcc IsPartyLFG error

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-TBC-Classic#57]
**Describe the bug**
Error on retail only API on login

**Do you have an error log of what happened?**
```
3x DBM-Core\DBM-Core-c02ce28.lua:6528: attempt to call global 'IsPartyLFG' (a nil value)
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:6528: in function 'StartLogging'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:4166: in function 'func'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:1906: in function <DBM-Core\DBM-Core.lua:1897>
```

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
2.5.12-10-gb11edb6-bcc

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by QartemisT** [comment]
Amazing work with reporting these issues, big thank you <3
