### ISSUE TITLE
latest alpha C_Scenario

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-TBC-Classic#58]
**Describe the bug**

**Do you have an error log of what happened?**
```
1x DBM-Core\DBM-Core-c02ce28.lua:5942: attempt to index global 'C_Scenario' (a nil value)
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:5942: in function 'StartCombat'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:5593: in function 'handler'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:911: in function <DBM-Core\DBM-Core.lua:898>
```

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by Road-block** [comment]
Ehm.. not sure which alpha version I got, raiding and it's hard to multitask

**Comment by QartemisT** [comment]
Once again, amazing find! Appreciate it.
