### ISSUE TITLE
 2.5.12-10-gb11edb6-bcc IsInScenarioGroup

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-TBC-Classic#59]
**Describe the bug**

**Do you have an error log of what happened?**
```
1x DBM-Core\DBM-Core-52a5bd9.lua:5791: attempt to call global 'IsInScenarioGroup' (a nil value)
[string "@DBM-Core\DBM-Core-52a5bd9.lua"]:5791: in function 'func'
[string "@DBM-Core\DBM-Core-52a5bd9.lua"]:1906: in function <DBM-Core\DBM-Core.lua:1897>
```

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
2.5.12-10-gb11edb6-bcc

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Thank you for helping beta test the tbc alpha. :D
