### ISSUE TITLE
alpha C_Scenario

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-TBC-Classic#60]
**Describe the bug**

**Do you have an error log of what happened?**
```
1x DBM-Core\DBM-Core-c02ce28.lua:5942: attempt to index global 'C_Scenario' (a nil value)
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:5942: in function 'StartCombat'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:5593: in function 'handler'
[string "@DBM-Core\DBM-Core-c02ce28.lua"]:911: in function <DBM-Core\DBM-Core.lua:898>
```

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
2.5.12-10-gb11edb6-bcc (possibly, I did a few updates back to back)

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by Road-block** [comment]
Last one, I stopped raiding for the evening 😝

**Comment by QartemisT** [comment]
Are you SURE you have teh latest alpha? The line of code here is;

`if isRetail and mod.addon.type == "SCENARIO" and C_Scenario.IsInScenario() then`, so it should break long before that C_Scenario check o.o

**Comment by Road-block** [comment]
> Are you SURE you have teh latest alpha? The line of code here is;
> 
> `if isRetail and mod.addon.type == "SCENARIO" and C_Scenario.IsInScenario() then`, so it should break long before that C_Scenario check o.o

I'm not sure, feel free to close.

**Comment by QartemisT** [comment]
Thanks G. I did recently just send you an email if you wanted to check that :)
