### ISSUE TITLE
Invalid TOC file format.

### ISSUE THREAD

**Issue by MyTechnoHunter** [DeadlyBossMods/DBM-TBC-Classic#65]
when downloading the DBM file from curseforge your toc file contains all the interface sections for the various version of the game..
![image](https://user-images.githubusercontent.com/55214545/134401341-0db161ec-5eca-4cc2-9032-17370216105f.png)

problem is the GAME does not respect that formatting.. it respects separate files with specific names.
![image](https://user-images.githubusercontent.com/55214545/134401695-eadecbe5-e4f5-4d09-89bb-19e52cf86db2.png)

as it is, i either enable loading out of date addons, edit the toc file (not hard to do) or create the separate toc files like above and edit the contents to use the correct version info on the ## Interface:
line.. 
please advise?  is this change a hoped for adaptation in the handling of toc files by the game? in which case i will ignore till the game can handle it.. if not it should be fixed

**Comment by QartemisT** [comment]
This should be fixed as of the latest commit. Apparently the packager stopped parsing TOC's for external projects (which DBM-Core is now, under DBM-Unified)
