### ISSUE TITLE
World events boss title 

### ISSUE THREAD

**Issue by BubuTurtle** [DeadlyBossMods/DBM-TBC-Classic#66]
Hi!
Is it normal that the boss name shown as like d286 in game?
I tried to add localization as usual by using such as 
L:SetGeneralLocalization{
	name = "Localized name"
}
But it still shows d286 in option frame.
Wonder if any way to solve it.

Thanks a lot :)

**Comment by MysticalOS** [comment]
Code in core should fill in name with SetGeneralLocalization

Maybe put it in wrong file or encoding? I'm gonna add it and it should work

**Comment by BubuTurtle** [comment]
Seems not work for me =( 
If it work for you, maybe the reason is i'm not using english client or reason.
Thanks for replying!

**Comment by BubuTurtle** [comment]
It work after core update. Thanks =)
