### ISSUE TITLE
In DBM-Serpentshrine/Fathomlord.lua, use NPCID instead of using spellID?

### ISSUE THREAD

**Issue by Mini-Dragon** [DeadlyBossMods/DBM-TBC-Classic#67]
local specWarnTotem		= mod:NewSpecialWarningSwitch(38236, "Dps", nil, nil, 1, 2)

One of my friends said the trigger should be NPCID=22091 or something? Because in zhCN, this two stuffs were translated in two different names (spell=飞火图腾 NPC=溅火图腾). But in enUS, same.

**Comment by MysticalOS** [comment]
That's correct spellid to use. there is no way to auto translate npc names so that's not doable. as long as  alert works, unlikely to change it
