### ISSUE TITLE
KaelThas Phase 4 timer is inaccuracy

### ISSUE THREAD

**Issue by zxfishhack** [DeadlyBossMods/DBM-TBC-Classic#70]
https://github.com/DeadlyBossMods/DBM-TBC-Classic/blob/a3f6b50de6f5a512a9616ce86a659b7905731dcb/DBM-TheEye/KaelThas.lua#L242-L249

KaelThas Phase 4 timer is longer than it need, from the comment and the code, perhaps Line 248 might be `timerPhase:Start(113)`?

**Comment by MysticalOS** [comment]
I watched streams first week and he seemed to activate when timer was at 0, is he now activating 10 seconds before timer expires?

**Comment by zxfishhack** [comment]
video: https://b23.tv/HZOzjh

**Comment by zxfishhack** [comment]
video: https://b23.tv/HZOzjh

**Comment by zxfishhack** [comment]
KaelThas yell at about 5:31, timer show at about 5:41, and the timer is 1:53 (i modify L248 manual.)

**Comment by MysticalOS** [comment]
I will push this timer change. Thanks for report
