### ISSUE TITLE
Al'ar dive bomb timer no longer showing up in DBM-2.5.18-bcc

### ISSUE THREAD

**Issue by selena81792** [DeadlyBossMods/DBM-TBC-Classic#78]
**Describe the bug**
After updating to DBM-2.5.18-bcc, Al'ar no longer shows dive bomb timer. Downgrading to DBM-2.5.17-bcc made it appear again.

**Do you have an error log of what happened?**
Since the update, I am raiding on 3 characters and all 3 did not have dive bomb timer. I made sure to enable dive bomb timer in the setting before pull for all 3, and eventually gave up and downgraded to DBM-2.5.17-bcc. After that dive bomb timer appeared again today without changing any settings.

**Was it working in a previous version? If yes, which was the last good one?**
DBM-2.5.17-bcc

**Additional context**
Does anyone else experience this problem? Sorry if this isn't the right place to post! Hope my bug report was useful.

**Comment by MysticalOS** [comment]
any lua errors? it has to be the changes to scheduler that broke that, but if it didn't work it probably through an error

**Comment by MysticalOS** [comment]
Pretty sure I found cause and pushed fix. I'll double check fix on a live solo run of alar though in a few minutes

**Comment by selena81792** [comment]
thank you for the very quick fix! keen to update to the new release.
