### ISSUE TITLE
Void Zones not announced against Netherspite

### ISSUE THREAD

**Issue by BreakBB** [DeadlyBossMods/DBM-TBC-Classic#91]
**Describe the bug**

The boss [Netherspite](https://tbc.wowhead.com/npc=15689/netherspite) in Karazhan casts [Void Zone](https://tbc.wowhead.com/spell=37063/void-zone) which leaves a void zone below a random player. As with other void zones I would assume DBM should announce when you stand in such a zone and take damage of it. However DBM announces nothing towards this Void Zone.

DBM has an option for casting this spell though (see screenshot below).

According to [the Warcraft Logs of tonight](https://classic.warcraftlogs.com/reports/dZK48mFJ91NXYznW/#fight=71&hostility=1&type=casts&source=150) the spell that damages the player when standing in a void zone is [Consumption](https://tbc.wowhead.com/spell=28865/consumption).

**Do you have an error log of what happened?**

No error.

**To Reproduce**

Fight Netherspite in Karazhan and stand in a Void Zone.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/33514570/151246802-d347abe4-5b74-40dc-a3d6-5508dcf149be.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nope

**Which version of DeadlyBossMods are you using?**
2.5.24

**Was it working in a previous version? If yes, which was the last good one?**
No, I don't remember having any fight against Netherspite in Classic TBC in which DBM announced the void zones.

**Additional context**
-

**Comment by MysticalOS** [comment]
i see 37063 not consumption. but fixing none the less

**Comment by BreakBB** [comment]
Insane response time @MysticalOS 🤩 Appreciate it 👍🏻

**Comment by BreakBB** [comment]
Just tested this and it still doesn't work. Another log showing the consumption source of damage: https://classic.warcraftlogs.com/reports/J6WMv8xr3zqDAGfH/#fight=60&type=damage-taken&source=15

**Comment by MysticalOS** [comment]
That's weird, first log you showed me was definitely 37063 but this new one is 28865

I'll just keep both in mod

**Comment by BreakBB** [comment]
My bad then, sorry 🙈
